### ISSUE TITLE
i cant install TFL

### ISSUE THREAD

**Issue by sonick13** [terminalforlife/PerlProjects#1]
i cant found TFL 
i try cpan TFL and many ways but i cant install it
some help will be great

**Comment by terminalforlife** [comment]
It's TFL.pm (libtfl-perl) which is in this repository.

If you have Cito, it's an easy solution, but skip this option if you're on Debian or Ubuntu (or distributions based thereon):

```
sudo cito -r terminalforlife PerlProjects master source/TFL.pm
```

If you _are_ on Debian or Ubuntu, you can use the Debian package in the [DEB-Packages](https://github.com/terminalforlife/DEB-Packages) repository.

**Comment by sonick13** [comment]
Thanks i try manually,iam running cygwin

**Comment by terminalforlife** [comment]
Oooh, okay. Yeah, manually is your best bet then. Are you Windows 10 (not S)? It has that WSL thing. I tried that out on a server recently and was quite impressed. Worth giving it a go.

**Comment by sonick13** [comment]
yeah but cygwin is best,
wsl missing many stuff
i have wsl arch linux and ubuntu and kali linux
the best channel for linux, thanks always i be first who do like thanks again
this my channel youtube
https://www.youtube.com/channel/UCNgf7ZmNdgJ32T7VXMkMRMA?view_as=subscriber

**Comment by terminalforlife** [comment]
Did it work? Issue solved?
